### ISSUE TITLE
Disable output truncation

### ISSUE THREAD

**Issue by aripollak** [heroku/heroku-local#17]
The switch to node-foreman caused output lines to be truncated at the window width, which is pretty unfriendly to development. I think -w should be passed to node-foreman by default.

**Comment by jdx** [comment]
I have a PR in to fix this https://github.com/strongloop/node-foreman/pull/103

**Comment by josegrad** [comment]
This is very anoying in development. Any tricks to solve it before a fix is available?

**Comment by aripollak** [comment]
Seems to be fixed now. node-foreman wraps lines, which is still annoying, but not as bad.
