### ISSUE TITLE
Document concurrency and multiple process types

### ISSUE THREAD

**Issue by bjeanes** [heroku/heroku-local#21]
I know `--concurrency` is deprecated.

However, you may or may not realise that `node-foreman` still supports it and so does `heroku local`:

```
$ heroku local web=1,worker=2
5:13:52 PM web.1    |  [47645] Puma starting in cluster mode...
5:13:52 PM web.1    |  [47645] * Version 2.11.0 (ruby 1.9.3-p551), codename: Intrepid Squirrel
5:13:52 PM web.1    |  [47645] * Min threads: 1, max threads: 1
5:13:52 PM web.1    |  [47645] * Environment: development
5:13:52 PM web.1    |  [47645] * Process workers: 2
5:13:52 PM web.1    |  [47645] * Preloading application
5:14:10 PM web.1    |  [47645] * Listening on tcp://0.0.0.0:5000
5:14:10 PM worker.1 |  [Worker(host:Bos-MacBook.local pid:47646)] Starting job worker
5:14:10 PM worker.2 |  [Worker(host:Bos-MacBook.local pid:47647)] Starting job worker
5:14:10 PM web.1    |  [47645] Use Ctrl-C to stop
5:14:10 PM web.1    |  [47645] - Worker 0 (pid: 47655) booted, phase: 0
5:14:10 PM web.1    |  [47645] - Worker 1 (pid: 47656) booted, phase: 0
```

I suggest tweaking the usage examples to include this functionality:

```
Examples:

  heroku local
  heroku local web
  heroku local web=2
  heroku local web=1,worker=2
  heroku local -f Procfile.test -e .env.test
```

Probably also could change the deprecation error for `--concurrency`...

**Comment by nruth** [comment]
It'd be helpful to have `heroku local web,worker` in the examples as I thought it wasn't possible, but seems to work just fine. 

This lets us use the production Procfiles but filter out a bunch of extra worker definitions with specific queue priorities that aren't interesting for dev.

**Comment by bjeanes** [comment]
> This lets us use the production Procfiles but filter out a bunch of extra worker definitions with specific queue priorities that aren't interesting for dev.

Literally exactly what I'm doing too.
