### ISSUE TITLE
Cached node.js server files while running locally

### ISSUE THREAD

**Issue by ogoossens** [heroku/heroku-local#27]
**Dear all,**

is it possible that while working locally on my source and I run _heroku local web_ command, that the files are either cached, or taken from heroku servers?

**Somehow my workflow:**
- git pull
- node.js server files editing
- heroku local web (local test)

Does not work. I always have old files running as if the saved changes in node.js were ignored.

**Thank you**

**Oliver**

**Comment by jdx** [comment]
no it's not possible for any caching to be taking place or code to be taken from the heroku servers. local simply uses node-foreman to exec a command

**Comment by ogoossens** [comment]
Thank you for input, just wanted to have that clarified. Will do further testing in few hours. Thank you

**Comment by ogoossens** [comment]
Please delete this issue - it was just my mistake in code. Everything runs now.

**Comment by ogoossens** [comment]
Just for the explanation: My node.js server was giving me the same result all the time because of one simple reason. I might be hosting everything locally but when I don't change the socket parameter on my client - he still will connect to the Heroku remote one :D (my stupid mistake and I apologize). Thank you. O
