### ISSUE TITLE
Downloads from a non-organization owned repository, no checks on blob safety

### ISSUE THREAD

**Issue by omarkj** [heroku/heroku-local#3]
I was looking over how `heroku-local` goes about downloading `forgo` to run and noticed that a build gets downloaded from a repository that's [not owned by Heroku](https://github.com/heroku/heroku-local/blob/master/lib/forego.js#L99). Additionally, no checks are done on the [downloaded file](https://github.com/heroku/heroku-local/blob/master/lib/forego.js#L68) (such as checking `sha` signatures etc) and the blob then gets run.

This is insecure. The version of `forgo` should probably be pinned and the sha signatures of the blobs distributed with the plugin itself (or better yet, the actual blobs). That is my no means unbreakable but provides some very basic checks.

**Comment by jdx** [comment]
thanks for posting, and you're right. I think the right solution is to pin it against a sha signature as you mention.
