### ISSUE TITLE
heroku local web not working with Node and ClearDB.

### ISSUE THREAD

**Issue by tadwhitaker** [heroku/heroku-local#6]
We're running an Express/Node/MySql/Sequelize stack and are following the official Heroku Node tutorial. It is successfully deployed, but running heroku local web produces the following:

forego | starting web.1 on port 5000

web.1  | events.js:141

Any help would be greatly appreciated.

**Comment by jdx** [comment]
it's this issue https://github.com/ddollar/forego/issues/67

**Comment by HanSooloo** [comment]
Does this mean heroku-local will pick this up in the next update?  As of 2015-11-01, I am still not able to get error text if I start my Flask project using `heroku local` syntax.

**Comment by jdx** [comment]
whenever it's released I will update it
