### ISSUE TITLE
ERR_CONNECTION_REFUSED http://localhost:5000

### ISSUE THREAD

**Issue by wulfgarpro** [heroku/heroku-local#7]
When I run:

`heroku local web`

I get:

ERR_CONNECTION_REFUSED

in my web browser when I go to:

http://localhost:5000

How can I get some more debug?

**Comment by jdx** [comment]
you probably have something running on that port

**Comment by wulfgarpro** [comment]
That was my first thought - nope.

Also, no firewall causing issues.

**Comment by jdx** [comment]
Does it work without using heroku local?

**Comment by wulfgarpro** [comment]
Fixed

Issue was my Procfile was calling the wrong runner.

web: node app.js

changed to:

web: node bin/www
